CREATE TABLE Usuario (
	Login VARCHAR(30) NOT NULL,
	Nome_Usuario VARCHAR(30) NOT NULL,
	CidadeNatal VARCHAR(30) NULL,
	PRIMARY KEY(Login)
);

CREATE TABLE Conhece (
	Login1 VARCHAR(30) NOT NULL,
	Login2 VARCHAR(30) NOT NULL,
	PRIMARY KEY(Login1, Login2),
	FOREIGN KEY(Login1)
		REFERENCES Usuario(Login)
			ON DELETE SET NULL
			ON UPDATE NO ACTION,
	FOREIGN KEY(Login2)
		REFERENCES Usuario(Login)
			ON DELETE SET NULL
			ON UPDATE NO ACTION
);


CREATE TABLE Filme(
	URI_Filme VARCHAR(100) NOT NULL,
	Nome_Filme VARCHAR(100) NOT NULL,
	Categorias VARCHAR(30) NOT NULL,
	PRIMARY KEY(URI_Filme)	
);


CREATE TABLE Categoria(
	ID INTEGER NOT NULL,
	Nome_categoria VARCHAR(30) NOT NULL,
	PRIMARY KEY(ID)
);


CREATE TABLE GostaFilme (
	Login VARCHAR(30) NOT NULL,
	URI_Filme VARCHAR(4) NOT NULL,
	Nota Integer NOT NULL,
	PRIMARY KEY(Login, URI_Filme),
	FOREIGN KEY(Login)
		REFERENCES Usuario(Login)
			ON DELETE SET NULL
			ON UPDATE NO ACTION,
	FOREIGN KEY(URI_Filme)
		REFERENCES Filme(URI_Filme)
			ON DELETE SET NULL
			ON UPDATE NO ACTION
);


CREATE TABLE Artista (
	URI_Artista VARCHAR(200) NOT NULL,
	Nome_Artista VARCHAR(50) NOT NULL,
	PRIMARY KEY (URI_Artista)
);


CREATE TABLE GostaArtista (
	Login VARCHAR(30) NOT NULL,
	URI_Artista VARCHAR(200) NOT NULL,
	Nota INTEGER NOT NULL,
	PRIMARY KEY(Login, URI_Artista),
	FOREIGN KEY(Login)
		REFERENCES Usuario(Login)
			ON DELETE SET NULL
			ON UPDATE NO ACTION,
	FOREIGN KEY(URI_Artista)
		REFERENCES Artista(URI_Artista)
			ON DELETE SET NULL
			ON UPDATE NO ACTION
);
